import type { Sailor } from './schema'

export interface EvidencePolicy {
  id: string
  claim: string
  owner: Sailor
  priority: 'P0' | 'P1' | 'P2'
  requiredEvidence: string[]
  processFailure: string
  repair: string
  source: string
}

export const CANONICAL_SOURCE_DOCS = [
  'docs/process/captain-os-lab/14-high-anger-case-studies.md',
  'docs/process/captain-os-lab/15-complexity-and-subcrew-escalation.md',
  'docs/process/captain-os-lab/17-runtime-contract-and-gates.md',
  'docs/process/captain-os-lab/18-implementation-spec-shadow-runner-v0.md',
  'docs/process/captain-os-lab/26-diamond-research-to-execution-protocol.md',
  'docs/process/captain-os-lab/27-no-false-done-and-autonomous-continuation.md',
  'docs/process/captain-os-lab/38-p0-operating-safety-stop-visual-span.md',
  'docs/process/captain-os-lab/43-cross-llm-swarm-runtime.md',
  'docs/process/captain-os-lab/23-captain-os-lab-master-execution-plan.md',
  'docs/process/captain-os-lab/24-captain-os-lab-acceptance-matrix.md',
]

const policy = (
  id: string,
  claim: string,
  owner: Sailor,
  priority: 'P0' | 'P1' | 'P2',
  requiredEvidence: string[],
  processFailure: string,
  repair: string,
  source = '17-runtime-contract-and-gates.md',
): EvidencePolicy => ({ id, claim, owner, priority, requiredEvidence, processFailure, repair, source })

export const BLOCK_POLICIES: Record<string, EvidencePolicy> = {
  missing_source_target_map: policy(
    'missing_source_target_map',
    'copy_exact requires a source object, target object, allowed differences, forbidden differences, and copy map',
    'Surface',
    'P0',
    ['copy-map.json', 'source object', 'target object', 'allowed differences', 'forbidden differences'],
    'copy_exact was treated as creative build or local implementation',
    'Create the copy map before implementation and block unapproved creative deviation',
  ),
  missing_golden_comparison: policy(
    'missing_golden_comparison',
    'copy_exact requires a golden comparison against the accepted precedent',
    'QA',
    'P0',
    ['golden screenshot/code/data comparison', 'deviation log'],
    'render or route existence was accepted as fidelity proof',
    'Compare source and target against the nearest known-good object',
  ),
  acceptance_object_mismatch_risk: policy(
    'acceptance_object_mismatch_risk',
    'Captain must prove the same object Anton will inspect',
    'StarPom',
    'P0',
    ['accepted inspection object', 'visible result', 'user-value readout'],
    'evidence proved a smaller object than the user inspected',
    'Name the inspection object and bind evidence to it',
  ),
  missing_paragraph_source_fidelity: policy(
    'missing_paragraph_source_fidelity',
    'source-bearing content needs paragraph-level source fidelity',
    'CMS',
    'P0',
    ['paragraph source map', 'claim-to-link preservation proof'],
    'source count replaced source fidelity',
    'Map every source-bearing paragraph to preserved links',
  ),
  missing_source_diff: policy(
    'missing_source_diff',
    'source import/repair needs a source diff, not only rendered count',
    'Context',
    'P1',
    ['source diff', 'before/after source references'],
    'source-of-truth drift was not made visible',
    'Attach a source diff and rerun source smoke',
  ),
  missing_actual_input_modality: policy(
    'missing_actual_input_modality',
    'input bugs need evidence from the actual user modality',
    'QA',
    'P0',
    ['Mac trackpad/manual input evidence', 'real interaction trace'],
    'synthetic input proof did not cover the failing modality',
    'Reproduce with the actual modality or record accepted risk',
  ),
  synthetic_evidence_risk: policy(
    'synthetic_evidence_risk',
    'synthetic evidence cannot close a user-modality failure by itself',
    'StarPom',
    'P1',
    ['synthetic-vs-real evidence note', 'manual verification'],
    'automation proved the wrong behavior slice',
    'Add manual verification or keep the claim blocked',
  ),
  missing_prior_interaction_baseline: policy(
    'missing_prior_interaction_baseline',
    'regression repair needs the prior accepted interaction baseline',
    'Context',
    'P0',
    ['accepted baseline', 'before regression behavior'],
    'repair optimized current behavior while losing accepted behavior',
    'Promote the accepted baseline before changing code',
  ),
  missing_regression_proof: policy(
    'missing_regression_proof',
    'preserve_and_repair needs regression proof after the fix',
    'QA',
    'P0',
    ['before/after proof', 'rerun after fix', 'preserved behavior list'],
    'fix was reported without proving preserved behavior',
    'Run the accepted behavior scenario again after repair',
  ),
  missing_system_grammar_path: policy(
    'missing_system_grammar_path',
    'system grammar changes need a UI Library or shared-standard path',
    'Knowledge',
    'P0',
    ['system grammar path', 'standard/component registry reference'],
    'page-local polish bypassed the standard',
    'Route the change through the system grammar before runtime use',
  ),
  page_local_polish_risk: policy(
    'page_local_polish_risk',
    'repeated visual drift cannot be closed as page-local polish',
    'Surface',
    'P1',
    ['reusable rule', 'standardized pattern', 'fixture/guard'],
    'visual repair solved one page while leaving recurrence open',
    'Promote the pattern or add a recurrence guard',
  ),
  missing_precedent_map: policy(
    'missing_precedent_map',
    'workstation/shell changes need a known-good precedent map',
    'Surface',
    'P0',
    ['surface precedent', 'component precedent', 'token source'],
    'new local shell behavior replaced canonical precedent',
    'Map the target surface to WorkstationFrame and UI Library contracts',
  ),
  missing_forbidden_scope: policy(
    'missing_forbidden_scope',
    'captain packet needs forbidden scope for fidelity-critical tasks',
    'Captain',
    'P1',
    ['forbidden scope', 'stop conditions'],
    'implementation expanded beyond the user intent',
    'State what must not change before editing',
  ),
  missing_source_of_truth_resolution: policy(
    'missing_source_of_truth_resolution',
    'two-source visual truth needs one declared source of truth',
    'Captain',
    'P0',
    ['chosen source-of-truth layer', 'baked visual proof'],
    'browser/editor/source edits fought each other',
    'Declare the truth layer and block edits until it is baked',
  ),
  two_source_truth_risk: policy(
    'two_source_truth_risk',
    'manual visual placement cannot coexist with source edits without protocol',
    'QA',
    'P0',
    ['manual placement preservation proof', 'rerender screenshot'],
    'manual geometry was overwritten by source changes',
    'Bake or rebase manual placement before further edits',
  ),
  text_only_acceptance_risk: policy(
    'text_only_acceptance_risk',
    'visual/stage work cannot close on text-only acceptance',
    'QA',
    'P0',
    ['rendered screenshot', 'visual QA notes'],
    'reported improvements were not tied to visual evidence',
    'Attach rendered visual proof and compare against requested stage',
  ),
  missing_stage_visual_evidence: policy(
    'missing_stage_visual_evidence',
    'stage/deck changes need stage-specific visual evidence',
    'Surface',
    'P1',
    ['stage screenshot', 'geometry readout'],
    'deck evidence did not prove the visible stage state',
    'Run the stage render and record geometry evidence',
  ),
  missing_save_reload_publish_proof: policy(
    'missing_save_reload_publish_proof',
    'CMS persistence needs save/reload/publish proof',
    'CMS',
    'P0',
    ['save proof', 'reload proof', 'publish or explicit disabled-state proof'],
    'fake persistence or UI state was accepted as data persistence',
    'Run the persistence loop and block disabled fake controls',
  ),
  fake_persistence_risk: policy(
    'fake_persistence_risk',
    'disabled or local-only CMS controls must not imply persistence',
    'StarPom',
    'P0',
    ['disabled-state explanation', 'data write/read proof'],
    'UI implied data persistence that did not exist',
    'Make persistence state explicit and add save/reload evidence',
  ),
  missing_security_negative_proof: policy(
    'missing_security_negative_proof',
    'public/studio/security readiness needs negative proof',
    'Security',
    'P0',
    ['public negative route proof', 'bundle/chunk exposure proof', 'auth boundary proof'],
    'security/public readiness was claimed from positive render only',
    'Prove forbidden public exposure does not exist',
  ),
  public_boundary_overclaim: policy(
    'public_boundary_overclaim',
    'studio/public boundary claims cannot overstate access control',
    'StarPom',
    'P0',
    ['boundary contract reference', 'negative proof', 'residual risk'],
    'client-visible or interim access wall was described as final security',
    'Downgrade claim or provide real boundary evidence',
  ),
  missing_dirty_worktree_scan: policy(
    'missing_dirty_worktree_scan',
    'PR readiness needs dirty-worktree and ownership scan',
    'Shipping',
    'P0',
    ['git status', 'owned/unowned diff map'],
    'readiness ignored unrelated or user-owned changes',
    'Scan dirty tree and isolate the current scope',
  ),
  missing_review_ci_state: policy(
    'missing_review_ci_state',
    'PR readiness needs review and CI state',
    'Shipping',
    'P1',
    ['CI/check state', 'review thread state', 'unresolved comment state'],
    'PR was called ready without review conveyor evidence',
    'Attach current CI and review state',
  ),
  review_prose_without_fix_queue: policy(
    'review_prose_without_fix_queue',
    'review findings need owner-bound fix queue entries',
    'StarPom',
    'P0',
    ['fix-queue.json', 'owner', 'severity', 'status'],
    'findings stayed as prose and were not executable',
    'Create a fix queue or explicitly defer with risk',
  ),
  missing_owner_bound_findings: policy(
    'missing_owner_bound_findings',
    'multi-finding reviews need clear owners and closure state',
    'QA',
    'P1',
    ['owner-bound findings', 'closure reason'],
    'review overload created no accountable next action',
    'Assign findings to owner lanes and status',
  ),
  missed_russian_intent_routing: policy(
    'missed_russian_intent_routing',
    'Russian mixed prompts need intent routing before execution',
    'Captain',
    'P1',
    ['intent routing note', 'hook/next action split'],
    'assistant answered the wrong part of a mixed Russian request',
    'Separate instruction, emotion, scope, and next action',
  ),
  missing_context_radius_artifact: policy(
    'missing_context_radius_artifact',
    'context/radius-sensitive work needs a context radius artifact',
    'Context',
    'P0',
    ['session context pack', 'blast/radius map', 'affected contracts'],
    'nearest-file context was mistaken for full radius',
    'Produce the radius artifact before implementation',
  ),
  missing_rag_freshness: policy(
    'missing_rag_freshness',
    'RAG/session context needs freshness proof',
    'Context',
    'P1',
    ['freshness timestamp', 'source docs read list'],
    'stale or partial context drove the plan',
    'Record what was read and when',
  ),
  rag_context_pack_missing: policy(
    'rag_context_pack_missing',
    'Every Tier 1+ Captain packet needs a scoped RAG/context pack before packet or crew dispatch',
    'Context',
    'P0',
    ['context-runtime.json', 'rag pack refs', 'source docs read list'],
    'Captain or sailors executed from naked prompt context instead of scoped RAG/session context',
    'Attach the relevant RAG/session pack to the Captain packet or downgrade to a true T0 answer',
    '43-cross-llm-swarm-runtime.md',
  ),
  session_pack_missing: policy(
    'session_pack_missing',
    'D3+ and Hard Work/Octopus tasks need a scoped session pack before execution',
    'Context',
    'P0',
    ['session-pack ref', 'task digest', 'operator intent summary'],
    'major work started without preserved session intent and constraints',
    'Create or attach a session pack before packet, crew, or final claim',
    '43-cross-llm-swarm-runtime.md',
  ),
  splash_radius_hook_missing: policy(
    'splash_radius_hook_missing',
    'Every non-trivial Captain packet needs a splash/blast-radius hook before packet and crew dispatch',
    'Context',
    'P0',
    ['splash-radius.json', 'changed scope refs', 'forbidden scope refs'],
    'implementation started without knowing affected neighboring surfaces and contracts',
    'Run or attach splash/blast-radius output before crew dispatch',
    '43-cross-llm-swarm-runtime.md',
  ),
  cross_llm_required_verdict_missing: policy(
    'cross_llm_required_verdict_missing',
    'Claude Code plan/code/final review verdict is required for SLA-triggered final claims',
    'JudgePool',
    'P0',
    ['cross-llm-sla.json', 'Claude Code P10F verdict JSON', 'merged Captain decision'],
    'Captain claimed readiness without the required independent second-runtime verdict',
    'Get the Claude Code verdict or remove/downgrade the final claim',
    '43-cross-llm-swarm-runtime.md',
  ),
  evidence_aggregation_report_missing: policy(
    'evidence_aggregation_report_missing',
    'Five-agent/P10F runtime evidence needs one unified place to inspect artifacts and decisions',
    'QA',
    'P1',
    ['evidence-aggregation.json', 'run artifact refs', 'P10F evidence level'],
    'evidence was scattered across chats/runs and became hard to inspect',
    'Write the unified evidence aggregation map and link any durable tracker',
    '43-cross-llm-swarm-runtime.md',
  ),
  missing_final_claim_evidence: policy(
    'missing_final_claim_evidence',
    'final readiness claims need evidence bound to the accepted object',
    'StarPom',
    'P0',
    ['accepted object evidence', 'test/smoke evidence', 'residual risk'],
    'green/done claim lacked closure evidence',
    'Block final claim until evidence rows pass',
  ),
  missing_diamond_research_corpus: policy(
    'missing_diamond_research_corpus',
    'Diamond research requires corpus map, source freshness, excluded sources, and confidence limits',
    'Context',
    'P0',
    ['research-context.json', 'corpus map', 'freshness notes', 'confidence limits'],
    'deep research became confidence theatre without a bounded source corpus',
    'Create a research context artifact before spec freeze',
    '26-diamond-research-to-execution-protocol.md',
  ),
  missing_research_to_spec_trace: policy(
    'missing_research_to_spec_trace',
    'Every actionable research finding must trace to an artifact/page/task spec',
    'Knowledge',
    'P0',
    ['findings-ledger.json', 'artifact-specs.json', 'finding -> spec trace'],
    'research findings stayed as prose and did not become executable acceptance',
    'Link each P0/P1 finding to at least one spec row',
    '26-diamond-research-to-execution-protocol.md',
  ),
  artifact_spec_without_acceptance_matrix: policy(
    'artifact_spec_without_acceptance_matrix',
    'Artifact/page/task specs require prioritized acceptance rows',
    'QA',
    'P0',
    ['artifact-specs.json', 'priority-checklists.json', 'P0/P1/P2 rows'],
    'spec existed but had no testable acceptance contract',
    'Create testable checklist rows with owner and evidence',
    '26-diamond-research-to-execution-protocol.md',
  ),
  checklist_row_without_owner_evidence: policy(
    'checklist_row_without_owner_evidence',
    'Checklist rows require owner, evidence type, blocking flag, status, and rerun rule',
    'QA',
    'P0',
    ['owner', 'required evidence', 'blocking status', 'rerun status'],
    'checklist green state could be closed without evidence',
    'Add owner/evidence/rerun fields or block closure',
    '26-diamond-research-to-execution-protocol.md',
  ),
  sailor_verdict_without_artifact: policy(
    'sailor_verdict_without_artifact',
    'Sailor verdicts require concrete artifact, path, diff, or evidence note',
    'StarPom',
    'P1',
    ['sailor output artifact', 'path or evidence reference'],
    'independent sailors agreed in prose without executable output',
    'Require artifact-bound sailor outputs before synthesis',
    '26-diamond-research-to-execution-protocol.md',
  ),
  sailor_ownership_gap: policy(
    'sailor_ownership_gap',
    'Every required sailor needs non-overlapping ownership or Captain conflict resolution',
    'Captain',
    'P1',
    ['autonomy-envelope.json', 'ownership map', 'conflict resolution'],
    'multiple sailors owned the same claim without accountability',
    'Assign owner lanes and record overlap resolution',
    '26-diamond-research-to-execution-protocol.md',
  ),
  evidence_closure_without_rerun: policy(
    'evidence_closure_without_rerun',
    'Changed claims require rerun evidence after fix',
    'QA',
    'P0',
    ['rerun status', 'fresh evidence after fix'],
    'finding was marked fixed narratively without rerun',
    'Rerun targeted evidence or keep the claim blocked',
    '26-diamond-research-to-execution-protocol.md',
  ),
  starpom_closeout_without_claim_binding: policy(
    'starpom_closeout_without_claim_binding',
    'StarPom closeout must enumerate closed, blocked, and accepted-risk claims',
    'StarPom',
    'P0',
    ['closure-matrix.json', 'claim bindings', 'blocked claims'],
    'StarPom checked that process happened rather than that claims were proven',
    'Bind StarPom verdict to evidence rows and claim ids',
    '26-diamond-research-to-execution-protocol.md',
  ),
  accepted_risk_without_controls: policy(
    'accepted_risk_without_controls',
    'Accepted risk requires owner, consequence, expiry, tracking, compensating control, and claim limits',
    'StarPom',
    'P0',
    ['accepted-risks.json', 'owner', 'consequence', 'expiry', 'tracking', 'compensating control'],
    'risk was accepted as a vague bypass for incomplete evidence',
    'Add complete accepted-risk controls or keep product closure blocked',
    '26-diamond-research-to-execution-protocol.md',
  ),
  methodology_overclaims_product: policy(
    'methodology_overclaims_product',
    'Methodology readiness must not be reported as product/result readiness',
    'StarPom',
    'P0',
    ['separate methodology status', 'separate product closure status'],
    'process/spec readiness was overclaimed as accepted result',
    'Separate ready_for_execution from accepted_full',
    '26-diamond-research-to-execution-protocol.md',
  ),
  execution_plan_missing_required_fields: policy(
    'execution_plan_missing_required_fields',
    'Execution plans require phases, owners, dependencies, allowed/forbidden scope, evidence, and stop conditions',
    'Shipping',
    'P1',
    ['execution-plan-validation.json', 'phase evidence', 'scope and stop conditions'],
    'sequence-only plan could not preserve depth during implementation',
    'Add an execution plan validator row before implementation',
    '26-diamond-research-to-execution-protocol.md',
  ),
  open_work_inventory_missing: policy(
    'open_work_inventory_missing',
    'Partial closure requires a completed/open/deferred work inventory before Captain can stop',
    'Captain',
    'P0',
    ['open-work inventory', 'completed rows', 'open rows', 'deferred rows with owner and reason'],
    'agent stopped after a personal slice without naming the remaining unfinished work',
    'Create an open-work inventory and bind every open row to owner, next action, and evidence',
    '27-no-false-done-and-autonomous-continuation.md',
  ),
  broad_done_claim_with_open_work: policy(
    'broad_done_claim_with_open_work',
    'Done/ready claims cannot exceed the closed checklist scope when open work remains',
    'StarPom',
    'P0',
    ['scope-vs-claim matrix', 'open rows', 'allowed final wording'],
    'agent claimed the whole request was done while remaining rows were still open',
    'Downgrade to accepted_partial or continue until the open rows close',
    '27-no-false-done-and-autonomous-continuation.md',
  ),
  partial_done_without_next_packet: policy(
    'partial_done_without_next_packet',
    'Accepted partial closure requires a bound next packet for every blocking/open row',
    'Shipping',
    'P0',
    ['next packet', 'owner lanes', 'evidence owed', 'stop conditions'],
    'partial progress became a stopping point instead of a continuation packet',
    'Write the next packet or keep executing within the current scope',
    '27-no-false-done-and-autonomous-continuation.md',
  ),
  premature_stop_with_open_work: policy(
    'premature_stop_with_open_work',
    'Captain cannot stop while blocking open rows remain unless a real stop condition or accepted risk is recorded',
    'Captain',
    'P0',
    ['stop condition', 'accepted risk or blocker', 'continuation decision'],
    'agent ended the turn because its personal slice felt complete, not because the work was actually closed',
    'Continue execution, escalate the blocker, or create a claim-bound next packet',
    '27-no-false-done-and-autonomous-continuation.md',
  ),
  stop_and_answer_required: policy(
    'stop_and_answer_required',
    'A direct user question or answer-first request must be answered before edits, tools, or repair execution',
    'Captain',
    'P0',
    ['direct answer artifact', 'no-action-before-answer proof'],
    'agent continued execution instead of answering the user question',
    'Stop, answer the direct question, then resume only after the answer exists',
    '38-p0-operating-safety-stop-visual-span.md',
  ),
  anger_incident_answer_required: policy(
    'anger_incident_answer_required',
    'Anger/frustration incident mode requires answer-first diagnosis before more work',
    'StarPom',
    'P0',
    ['incident answer', 'root miss diagnosis', 'no autonomous repair before answer'],
    'agent reacted to frustration by rushing into more edits',
    'Answer what failed, name the exact miss, and only then continue with a repair packet',
    '38-p0-operating-safety-stop-visual-span.md',
  ),
  visible_acceptance_missing: policy(
    'visible_acceptance_missing',
    'UI/screenshot/product work cannot close while requested visible acceptance objects remain open',
    'Surface',
    'P0',
    ['visible acceptance rows', 'fresh screenshot or visual proof', 'before/after object check'],
    'tests or contracts were treated as closure while the visible object was still wrong',
    'Close each visible row or report it as open with owner and next packet',
    '38-p0-operating-safety-stop-visual-span.md',
  ),
  user_request_result_mismatch: policy(
    'user_request_result_mismatch',
    'StarPom must compare the user-requested inspection object against the agent acceptance object',
    'StarPom',
    'P0',
    ['user request rows', 'result rows', 'diff of requested vs accepted object'],
    'agent proved a different object than the one Anton asked about',
    'Realign the acceptance object to the user request before final claim',
    '38-p0-operating-safety-stop-visual-span.md',
  ),
  span_of_control_violation: policy(
    'span_of_control_violation',
    'Captain cannot directly manage more than five active rows, tasks, blockers, or child lanes',
    'Captain',
    'P0',
    ['active row count', 'officer lane map'],
    'one overloaded Captain tried to manage too many active objects',
    'Split work into officer lanes with no more than five active children per owner',
    '38-p0-operating-safety-stop-visual-span.md',
  ),
  officer_hierarchy_missing: policy(
    'officer_hierarchy_missing',
    'More than five active rows requires an officer hierarchy before execution',
    'Knowledge',
    'P0',
    ['officer lanes', 'owner scope', 'child limits'],
    'large work was assigned as a flat Captain checklist',
    'Create Intent/Scope, Context/RAG, Domain, Execution, and StarPom/Acceptance lanes',
    '38-p0-operating-safety-stop-visual-span.md',
  ),
  context_budget_violation: policy(
    'context_budget_violation',
    'Agents must receive scoped context packets instead of broadcast full-history/full-doc context',
    'Context',
    'P0',
    ['context budget rows', 'allowed context per lane', 'forbidden broadcast context'],
    'all sailors received broad irrelevant context and overloaded',
    'Create per-role context budgets and remove broadcast context from task packets',
    '38-p0-operating-safety-stop-visual-span.md',
  ),
  captain_os_adapter_missing: policy(
    'captain_os_adapter_missing',
    'Captain OS/process/continuation audits must load the local adapter or explicitly report missing_adapter',
    'Runtime',
    'P0',
    ['.captain-os/project.yaml', '.captain-os/task-spine.yaml', 'CLAUDE.md or AGENTS.md managed block', 'missing_adapter verdict if unavailable'],
    'plain user prompt fell back to old cockpit docs and did not boot the P11 adapter',
    'Read the local Captain OS adapter and task spine, or stop with missing_adapter before claiming continuity readiness',
    '49-p11f-auto-bootstrap-canary.md',
  ),
  route_checklist_missing: policy(
    'route_checklist_missing',
    'Route/page work that depends on checklist closure requires a parseable checklist artifact',
    'QA',
    'P0',
    ['route checklist path', 'parsed checklist rows', 'open row inventory'],
    'agent relied on checklist language without a parseable route/page closure artifact',
    'Attach a parseable checklist artifact or block broad route/page claims',
    '27-no-false-done-and-autonomous-continuation.md',
  ),
}

export function getPolicy(blockId: string): EvidencePolicy {
  return BLOCK_POLICIES[blockId] ?? policy(
    blockId,
    `Missing evidence for ${blockId}`,
    'QA',
    'P1',
    [blockId],
    'required advisory block has no registry entry yet',
    'Add a policy registry entry or close with accepted risk',
    'fixture expected block',
  )
}
