export const intentModes = [
  'direct_answer',
  'copy_exact',
  'preserve_and_repair',
  'bounded_build',
  'system_refactor',
  'incident_repair',
  'strategy_design',
] as const

export const complexityTiers = ['T0', 'T1', 'T2', 'T3', 'T4'] as const
export const planDepths = ['D0', 'D1', 'D2', 'D3', 'D4', 'D5'] as const

export const captainModes = [
  'direct_answer',
  'mini_packet',
  'bounded_pr',
  'full_ship_cycle',
  'incident_repair',
  'strategy_packet',
] as const

export const labModes = ['shadow'] as const
export const verdicts = ['pass', 'fail', 'blocked', 'accepted_risk'] as const
export const evidenceVerdicts = ['pass', 'fail', 'blocked', 'accepted_risk', 'warning'] as const
export const claimTypes = [
  'classification',
  'research',
  'artifact_spec',
  'checklist',
  'sailor_output',
  'execution_plan',
  'accepted_risk',
  'starpom_closeout',
] as const

export const sailors = [
  'Captain',
  'StarPom',
  'Context',
  'QA',
  'Surface',
  'CMS',
  'Runtime',
  'Security',
  'Shipping',
  'Knowledge',
  'JudgePool',
] as const

export type IntentMode = (typeof intentModes)[number]
export type ComplexityTier = (typeof complexityTiers)[number]
export type PlanDepth = (typeof planDepths)[number]
export type CaptainMode = (typeof captainModes)[number]
export type LabMode = (typeof labModes)[number]
export type Verdict = (typeof verdicts)[number]
export type EvidenceVerdict = (typeof evidenceVerdicts)[number]
export type ClaimType = (typeof claimTypes)[number]
export type Sailor = (typeof sailors)[number]

export interface RiskScores {
  userIntent: number
  fidelity: number
  blastRadius: number
  history: number
  evidence: number
}

export interface FixtureExpected {
  intentMode: IntentMode
  minComplexityTier: ComplexityTier
  minPlanDepth: PlanDepth
  requiredBlocks: string[]
  nonBlockingWarnings?: string[]
  requiredSailors?: Sailor[]
}

export interface FixtureInput {
  id: string
  title: string
  task: string
  sourceCase: string
  tags: string[]
  expected: FixtureExpected
  context?: Record<string, string>
}

export interface LabInput {
  id: string
  title: string
  task: string
  issueId?: string
  promptFile?: string
  fixtureId?: string
  sourceCase?: string
  sourceDocs: string[]
  tags: string[]
  expected?: FixtureExpected
  context: Record<string, string>
}

export interface ClassificationArtifact {
  intentMode: IntentMode
  complexityTier: ComplexityTier
  planDepth: PlanDepth
  captainMode: CaptainMode
  riskScores: RiskScores
  triggeredRules: string[]
  matchedSignals: string[]
  escalationReason: string
  downgradeReason: string | null
  hardWorkRequired: boolean
  octopusRequired: boolean
  finalClaimGateRequired: boolean
  confidence: 'low' | 'medium' | 'high'
}

export interface PacketPreviewArtifact {
  goal: string
  allowedScope: string[]
  forbiddenScope: string[]
  sourceOfTruth: string[]
  contextNeeds: string[]
  blastRadiusNeeds: string[]
  acceptanceObjects: string[]
  evidencePlan: string[]
  stopConditions: string[]
}

export interface ContextRuntimeArtifact {
  ragRequired: boolean
  ragPackInjected: boolean
  ragPackRefs: string[]
  captainOsAdapterRequired: boolean
  captainOsAdapterStatus: 'present' | 'missing_adapter' | 'not_required'
  captainOsAdapterRefs: string[]
  sessionPackRequired: boolean
  sessionPackInjected: boolean
  sessionPackRefs: string[]
  contextBudgetApplied: boolean
  contextBudgetRefs: string[]
  autoInsertMode: 'explicit_refs' | 'autogenerated_from_task_and_source_docs'
  blocks: string[]
  nextAction: string
}

export interface SplashRadiusArtifact {
  required: boolean
  hookPosition: 'before_packet_and_crew'
  splashRadiusHookInjected: boolean
  blastRadiusRequired: boolean
  crossDomain: boolean
  changedScopeRefs: string[]
  affectedSurfaces: string[]
  forbiddenScopeRefs: string[]
  blocks: string[]
  nextAction: string
}

export type CrossLlmPhase = 'plan_review' | 'code_review' | 'final_claim_review'

export interface CrossLlmSlaArtifact {
  enabled: boolean
  provider: 'claude_code_local'
  readOnlyByDefault: true
  writeAccessAllowed: boolean
  requiredPhases: CrossLlmPhase[]
  optionalPhases: CrossLlmPhase[]
  forbiddenWhen: string[]
  maxTimeoutMinutes: number
  verdictRefs: string[]
  missingVerdicts: CrossLlmPhase[]
  p10fOutputSchemaRequired: true
  blocks: string[]
  nextAction: string
}

export interface EvidenceAggregationArtifact {
  enabled: true
  reportName: 'p10g-runtime-evidence-map'
  runArtifactRefs: string[]
  p10fEvidenceLevels: string[]
  fiveAgentReportExpected: boolean
  batchCollectorRequired: boolean
  dashboardReady: boolean
  blocks: string[]
  nextAction: string
}

export interface UserIntentRow {
  id: string
  userSaid: string
  targetSurface: string | null
  visibleObject: string | null
  requiredChange: string
  askIfAmbiguous: boolean
  status: 'open' | 'closed'
}

export interface VisibleAcceptanceRow {
  id: string
  visibleObject: string
  expectedState: string
  currentState: string | null
  evidenceRequired: string[]
  status: 'open' | 'closed'
}

export interface OfficerLane {
  id: string
  owner: Sailor
  scope: string[]
  maxChildren: number
  contextBudgetRefs: string[]
}

export type LaneMode = 'persistent_owner' | 'one_shot_reviewer' | 'read_only_judge' | 'temporary_contractor' | 'standing_review'
export type LaneStatus = 'queued' | 'active' | 'blocked' | 'review' | 'merged' | 'closed' | 'stale'

export interface LaneState {
  laneId: string
  title: string
  owner: Sailor
  ownerRegistryId: string
  runtimeId: string | null
  laneMode: LaneMode
  status: LaneStatus
  assignmentId: string
  heartbeatAt: string | null
  staleAfterMinutes: number
  allowedScope: string[]
  forbiddenScope: string[]
  locks: string[]
  dependencies: string[]
  conflictsWith: string[]
  contextRefs: string[]
  contextBudgetRefs: string[]
  laneMemoryRef: string
  acceptanceRows: string[]
  evidenceOwed: string[]
  evidenceRefs: string[]
  lastDelta: string
  decisions: string[]
  openQuestions: string[]
  blockers: string[]
  nextAction: string
  closeoutCriteria: string[]
  transferCriteria: string[]
}

export interface ContextBudgetRow {
  laneId: string
  owner: Sailor
  allowedContext: string[]
  forbiddenContext: string[]
  tokenBudgetHint: string
  violation: boolean
}

export type ProjectStage =
  | 'discovery'
  | 'planning'
  | 'delivery'
  | 'launch_opening'
  | 'incident_repair'
  | 'maintenance'

export interface DeliveryCalibrationArtifact {
  projectStage: ProjectStage
  outcomeUnit: string
  deliveryShareTarget: number
  qualityShareTarget: number
  safetyShareTarget: number
  processBudgetMax: number
  maxPlanningOnlyCycles: number
  minClosedOutcomesPerCycle: number
  namedDeliverableRequired: boolean
  gateCommand: string
  blocks: string[]
  nextAction: string
  currentCycle?: {
    id: string
    processShare: number
    deliveryShare: number
    qualityShare: number
    safetyShare: number
    namedDeliverables: string[]
    closedOutcomes: string[]
    planningOnlyCycles: number
    falseGreenRisk: boolean
    safetyEvidenceRefs: string[]
    qualityEvidenceRefs: string[]
    ownerDecisionRequired: boolean
    adjacentWorkActive: boolean
    nextActionBound: boolean
    reportingAttachedToOutcomes: boolean
  }
}

export type CriticalPathMovement =
  | 'moves_original_goal'
  | 'adjacent_planning_only'
  | 'evidence_only'
  | 'blocked_waiting_owner'
  | 'unknown'

export interface OperatingSafetyArtifact {
  directQuestionDetected: boolean
  answerRequiredBeforeAction: boolean
  angerIncidentMode: boolean
  productionOpeningGoalDetected: boolean
  operatorDecisionRequired: boolean
  ownerChoices: string[]
  criticalPathMovement: CriticalPathMovement
  adjacentPlanningSlicesAfterBlocker: number
  hoursAfterBlocker: number
  timeboxedBypassRequested: boolean
  seoHttp200OnlySignal: boolean
  seoParityMissing: boolean
  claimedSwarm: boolean
  p11hScoreGateActive: boolean
  swarmRuntimeScore: number | null
  captainImplementationShare: number | null
  productiveCriticalLaneArtifacts: number | null
  freshLaneOutputs: number | null
  activeLaneCount: number | null
  nextPacketState: string | null
  userIntentRows: UserIntentRow[]
  visualAcceptanceRows: VisibleAcceptanceRow[]
  missingVisibleObjects: string[]
  activeRowCount: number
  spanOfControlLimit: 5
  spanOfControlViolation: boolean
  officerHierarchyRequired: boolean
  officerHierarchyPresent: boolean
  officerLanes: OfficerLane[]
  contextBudgetRows: ContextBudgetRow[]
  contextBudgetViolations: string[]
  blocks: string[]
  nextAction: string
}

export interface CrewPlanArtifact {
  captainMode: CaptainMode
  requiredSailors: Sailor[]
  optionalSailors: Sailor[]
  judgePool: string[]
  starpomRequired: boolean
  officerLanes: OfficerLane[]
  contextBudget: ContextBudgetRow[]
  spanOfControlLimit: 5
  activeChildCount: number
  writeScopes: string[]
  forbiddenScopes: string[]
  subcrewPermissions: string[]
  captainOnlyReason: string | null
  executionModel: 'direct_answer' | 'single_lane' | 'parallel_lane_swarm'
  parallelLaneTarget: number
  laneMemoryRequired: boolean
  laneStates: LaneState[]
  falseParallelismBlocks: string[]
  deliveryCalibration: DeliveryCalibrationArtifact
  captainWorkerPolicy: 'orchestrator_only' | 'local_worker_allowed'
  autoDispatch: false
}

export interface EvidenceRow {
  id: string
  claimId: string
  claimType: ClaimType
  claim: string
  owner: Sailor
  priority: 'P0' | 'P1' | 'P2'
  userInspectionObject: string | null
  agentAcceptanceObject: string | null
  acceptanceObjectMatch: boolean | null
  changedScope: string[]
  requiredEvidence: string[]
  evidenceRefs: string[]
  freshness: string | null
  negativeProof: string | null
  rerunStatus: 'not_required' | 'required' | 'complete'
  verdict: EvidenceVerdict
  blocking: boolean
  missingEvidence: string[]
  source: string
  status: 'open' | 'closed' | 'warning'
}

export interface EvidenceMatrixArtifact {
  claims: string[]
  rows: EvidenceRow[]
  missingEvidence: string[]
  staleEvidence: string[]
  acceptanceObjectMismatches: string[]
  finalVerdict: EvidenceVerdict
}

export interface DiamondRequiredArtifact {
  required: boolean
  reason: string
  minimumDepth: PlanDepth
  requiredArtifacts: string[]
  status: 'not_required' | 'required'
}

export interface ResearchSource {
  path: string
  type: 'canonical_doc' | 'report' | 'screenshot' | 'fixture' | 'code' | 'issue' | 'unknown'
  freshness: 'current' | 'stale' | 'unknown'
  used: boolean
}

export interface ResearchContextArtifact {
  corpusMap: ResearchSource[]
  excludedSources: string[]
  confidenceLimits: string[]
  corpusComplete: boolean
}

export interface FindingArtifact {
  id: string
  source: string
  claim: string
  affectedObjects: string[]
  severity: 'P0' | 'P1' | 'P2'
  failureClass: 'fidelity' | 'first_fold' | 'source_truth' | 'security' | 'evidence' | 'workflow' | 'runtime' | 'methodology'
  mustBecome: string
  ownerLane: Sailor
  evidenceRequired: string[]
  artifactSpecRefs: string[]
}

export interface FindingsLedgerArtifact {
  findings: FindingArtifact[]
  parkingLot: string[]
}

export interface ArtifactSpec {
  id: string
  object: string
  objectType: 'page' | 'route' | 'workflow' | 'component' | 'data_contract' | 'process_artifact' | 'task'
  audience: 'Anton' | 'operator' | 'captain' | 'public' | 'internal' | 'agent'
  currentState: string
  targetState: string
  acceptanceObject: string
  nonGoals: string[]
  forbiddenDrift: string[]
  checklistRefs: string[]
  evidenceRefs: string[]
}

export interface ArtifactSpecsArtifact {
  specs: ArtifactSpec[]
}

export interface PriorityChecklistItem {
  id: string
  sourceRequirement: string
  owner: Sailor
  scope: string[]
  forbiddenScope: string[]
  acceptanceObject: string
  userInspectionObject: string | null
  agentAcceptanceObject: string | null
  acceptanceObjectMatch: boolean | null
  requiredEvidence: string[]
  negativeProofRequired: boolean
  status: 'pending' | 'pass' | 'fail' | 'blocked' | 'accepted_risk'
  blocking: boolean
  evidenceRefs: string[]
  rerunStatus: 'not_required' | 'required' | 'complete'
}

export interface PriorityChecklistsArtifact {
  items: PriorityChecklistItem[]
}

export interface SailorOwnership {
  sailor: Sailor
  owns: string[]
  mayDecide: string[]
  mustNotChange: string[]
  mustEscalateIf: string[]
  evidenceOwed: string[]
}

export interface AutonomyEnvelopeArtifact {
  envelopes: SailorOwnership[]
}

export interface ExecutionPlanValidationArtifact {
  verdict: EvidenceVerdict
  missingFields: string[]
  blockingClaims: string[]
}

export interface AcceptedRiskValidationArtifact {
  verdict: EvidenceVerdict
  acceptedRisks: Array<{
    id: string
    owner: Sailor | null
    consequence: string | null
    expiry: string | null
    tracking: string | null
    compensatingControl: string | null
    doesNotPermit: string[]
  }>
  blockingClaims: string[]
}

export interface ClosureMatrixArtifact {
  closureStatus: 'ready_for_owner_review_planning_only' | 'ready_for_execution' | 'accepted_partial' | 'blocked'
  claimBindings: Array<{
    claimId: string
    artifactRef: string | null
    evidenceRef: string | null
    verdict: EvidenceVerdict
  }>
  finalClaimAllowed: boolean
  blockedClaims: string[]
}

export interface RouteChecklistRow {
  id: string
  section: string
  text: string
  checked: boolean
  line: number
  routeRefs: string[]
}

export interface RouteChecklistSection {
  heading: string
  routeRefs: string[]
  totalRows: number
  checkedRows: number
  openRows: number
  rows: RouteChecklistRow[]
}

export interface RouteChecklistCoverageArtifact {
  path: string | null
  parsed: boolean
  parseError: string | null
  totalRows: number
  checkedRows: number
  openRows: number
  openBlockingRows: RouteChecklistRow[]
  sections: RouteChecklistSection[]
}

export interface DiamondArtifacts {
  diamondRequired: DiamondRequiredArtifact
  researchContext: ResearchContextArtifact
  findingsLedger: FindingsLedgerArtifact
  artifactSpecs: ArtifactSpecsArtifact
  priorityChecklists: PriorityChecklistsArtifact
  autonomyEnvelope: AutonomyEnvelopeArtifact
  executionPlanValidation: ExecutionPlanValidationArtifact
  acceptedRiskValidation: AcceptedRiskValidationArtifact
  closureMatrix: ClosureMatrixArtifact
  routeChecklistCoverage: RouteChecklistCoverageArtifact
  blockIds: string[]
}

export interface FixFinding {
  id: string
  claim: string
  owner: Sailor
  severity: 'P0' | 'P1' | 'P2'
  status: 'open' | 'fixed' | 'duplicate' | 'deferred' | 'accepted_risk' | 'no_op'
  evidenceRequired: string[]
  rerunRequired: boolean
  trackingLink: string | null
  closureReason: string | null
}

export interface FixQueueArtifact {
  findings: FixFinding[]
}

export interface StarPomVerdictArtifact {
  verdict: Verdict
  blockedClaims: string[]
  processFailures: string[]
  requiredRepairs: string[]
  acceptedRisks: string[]
  finalClaimAllowed: boolean
  productClosureAllowed: boolean
  specPackageClosureStatus: 'ready_for_owner_review_planning_only' | 'ready_for_execution' | 'blocked'
  productClosureStatus: 'not_evaluated' | 'blocked'
}

export interface ScorecardArtifact {
  modeAccuracy: string
  intentModeAccuracy: string
  complexityTierConfidence: string
  crewSufficiency: string
  evidenceSufficiency: string
  falseGreenRisk: 'low' | 'medium' | 'high'
  operatorBurdenRisk: 'low' | 'medium' | 'high'
  recommendedNextGate: string
  fixturesToCreate: string[]
}

export interface RunArtifact {
  runId: string
  createdAt: string
  mode: LabMode
  issueId: string | null
  trackingId: string
  readOnly: true
  inputPromptDigest: string
  sourceDocs: string[]
  gitRef: string
  outDir: string
  exitCode: number
}

export interface LabRunArtifacts {
  run: RunArtifact
  input: LabInput
  operatingSafety: OperatingSafetyArtifact
  contextRuntime: ContextRuntimeArtifact
  splashRadius: SplashRadiusArtifact
  crossLlmSla: CrossLlmSlaArtifact
  evidenceAggregation: EvidenceAggregationArtifact
  classification: ClassificationArtifact
  packetPreview: PacketPreviewArtifact
  crewPlan: CrewPlanArtifact
  diamond: DiamondArtifacts
  evidenceMatrix: EvidenceMatrixArtifact
  fixQueue: FixQueueArtifact
  starpomVerdict: StarPomVerdictArtifact
  scorecard: ScorecardArtifact
  synthesis: string
}

export type ExecutionStateId =
  | 'intake'
  | 'operating_safety'
  | 'classification'
  | 'context_envelope'
  | 'splash_radius'
  | 'packet'
  | 'crew'
  | 'diamond'
  | 'evidence'
  | 'executability'
  | 'cross_llm_sla'
  | 'starpom'
  | 'evidence_aggregation'
  | 'continuation'
  | 'next_packet'

export type ExecutionStateStatus = 'pass' | 'warning' | 'blocked' | 'pending'

export interface ExecutionState {
  id: ExecutionStateId
  status: ExecutionStateStatus
  owner: Sailor
  artifacts: string[]
  blockers: string[]
  nextAction: string
}

export type ExecutionDecision =
  | 'continue_now'
  | 'accepted_partial_next_packet'
  | 'blocked_external'
  | 'operator_decision_required'
  | 'ready_for_owner_review_planning_only'
  | 'ready_for_execution'

export interface ExecutionStateMachineArtifact {
  version: 'p10g-universal-advisory-v1'
  universal: true
  runId: string
  decision: ExecutionDecision
  allowedFinalClaim: false
  reason: string
  states: ExecutionState[]
  openWork: {
    operatingSafetyBlocks: string[]
    contextRuntimeBlocks: string[]
    splashRadiusBlocks: string[]
    crossLlmBlocks: string[]
    evidenceAggregationBlocks: string[]
    blockingEvidenceRows: string[]
    p9dBlocks: string[]
    fixQueueRows: string[]
    routeChecklistOpenRows: number
    nextPacketRequired: boolean
  }
  requiredNextAction: string
}

export interface AdvisoryMetricsArtifact {
  mode: 'advisory'
  universal: true
  falsePositiveRisk: 'low' | 'medium' | 'high'
  falseNegativeRisk: 'low' | 'medium' | 'high'
  operatorBurdenRisk: 'low' | 'medium' | 'high'
  preventedFailureSignals: string[]
  openBlockingCount: number
  operatingSafetyBlockCount: number
  contextRuntimeBlockCount: number
  splashRadiusBlockCount: number
  crossLlmBlockCount: number
  evidenceAggregationBlockCount: number
  p9dBlockCount: number
  missingEvidenceCount: number
  routeChecklistOpenRows: number
}

export interface AdvisoryReportArtifact {
  status: 'advisory_ready'
  blocking: false
  stateMachine: ExecutionStateMachineArtifact
  metrics: AdvisoryMetricsArtifact
  message: string
}

export type ExecutableSpecSourceFormat = 'yaml' | 'markdown'
export type ArtifactCompileStatus = 'pass' | 'blocked'
export const executableEvidenceRefTypes = ['file', 'artifact', 'command', 'url', 'negative_proof', 'note'] as const
export type ExecutableEvidenceRefType = (typeof executableEvidenceRefTypes)[number]

export interface ExecutableSpecEvidenceRef {
  type: ExecutableEvidenceRefType
  value: string
  producedAt: string | null
  gitRef: string | null
  exitCode: number | null
  changedScope: string[]
  generated: boolean
}

export interface ExecutableSpecEvidenceSource {
  id: string
  claimId: string
  refs: ExecutableSpecEvidenceRef[]
  freshness: 'current' | 'stale' | 'unknown'
  verifier: Sailor
}

export interface ExecutableSpecNextPacketRow {
  rowId: string
  owner: Sailor
  nextAction: string
  evidenceOwed: string[]
  stopCondition: string
  tracking: string
}

export interface ExecutableSpecNextPacket {
  required: boolean
  owner: Sailor
  nextAction: string
  reason: string
  artifactRef: string | null
  rows: ExecutableSpecNextPacketRow[]
}

export interface ExecutableSpecCoverageMapRow {
  object: string
  status: 'covered' | 'deferred' | 'accepted_risk'
  checklistRefs: string[]
  owner: Sailor
  reason: string
}

export interface ExecutableSpecAcceptedRisk {
  id: string
  claimId: string
  owner: Sailor
  consequence: string
  expiry: string
  tracking: string
  compensatingControl: string
  claimLimits: string[]
  revisitTrigger: string
}

export interface ExecutableSpecSourceArtifact {
  version: 1
  id: string
  title: string
  sourceFormat: ExecutableSpecSourceFormat
  sourcePath: string
  sourceDigest: string
  intentMode: IntentMode
  complexityTier: ComplexityTier
  planDepth: PlanDepth
  captainMode: CaptainMode
  owner: Sailor
  sourceDocs: string[]
  acceptanceObjects: string[]
  requestedObjects: string[]
  coverageMap: ExecutableSpecCoverageMapRow[]
  acceptedRisks: ExecutableSpecAcceptedRisk[]
  sailors: SailorOwnership[]
  checklist: PriorityChecklistItem[]
  evidence: ExecutableSpecEvidenceSource[]
  nextPacket: ExecutableSpecNextPacket
}

export interface CompiledChecklistArtifact {
  specId: string
  totalRows: number
  openRows: number
  openBlockingRows: PriorityChecklistItem[]
  rows: PriorityChecklistItem[]
  finalVerdict: EvidenceVerdict
}

export interface CompiledEvidenceArtifact {
  specId: string
  rows: ExecutableSpecEvidenceSource[]
  missingEvidenceRows: string[]
  staleEvidenceRows: string[]
  finalVerdict: EvidenceVerdict
}

export interface CompiledNextPacketArtifact extends ExecutableSpecNextPacket {
  specId: string
  openBlockingRows: string[]
}

export interface ExecutabilityValidationArtifact {
  specId: string
  status: ArtifactCompileStatus
  p9dBlocks: string[]
  p9dWarnings: string[]
  validators: Array<{
    id: string
    status: ArtifactCompileStatus
    blocks: string[]
  }>
}

export interface ArtifactCompileReportArtifact {
  runId: string
  createdAt: string
  trackingId: string
  sourcePath: string
  sourceDigest: string
  outDir: string
  status: ArtifactCompileStatus
  exitCode: 0 | 2
  compileBlocks: string[]
  p9dBlocks: string[]
  warnings: string[]
  artifactRefs: string[]
  contractCompileAllowed: boolean
  executionReady: boolean
  productClosureAllowed: false
}

export function tierValue(tier: ComplexityTier): number {
  return complexityTiers.indexOf(tier)
}

export function depthValue(depth: PlanDepth): number {
  return planDepths.indexOf(depth)
}

export function maxTier(...tiers: ComplexityTier[]): ComplexityTier {
  return tiers.reduce((max, tier) => (tierValue(tier) > tierValue(max) ? tier : max), 'T0' as ComplexityTier)
}

export function maxDepth(...depths: PlanDepth[]): PlanDepth {
  return depths.reduce((max, depth) => (depthValue(depth) > depthValue(max) ? depth : max), 'D0' as PlanDepth)
}

export function atLeastTier(actual: ComplexityTier, expected: ComplexityTier): boolean {
  return tierValue(actual) >= tierValue(expected)
}

export function atLeastDepth(actual: PlanDepth, expected: PlanDepth): boolean {
  return depthValue(actual) >= depthValue(expected)
}

export function isIntentMode(value: string): value is IntentMode {
  return (intentModes as readonly string[]).includes(value)
}

export function isComplexityTier(value: string): value is ComplexityTier {
  return (complexityTiers as readonly string[]).includes(value)
}

export function isPlanDepth(value: string): value is PlanDepth {
  return (planDepths as readonly string[]).includes(value)
}

export function isSailor(value: string): value is Sailor {
  return (sailors as readonly string[]).includes(value)
}

export function assertNever(value: never): never {
  throw new Error(`Unhandled Captain Lab value: ${String(value)}`)
}
